dotenv: .env

dependencies:
    # - <organization/repo>@<version>
    - aave/protocol-v2@1.0.1

compiler:
    evm_version: null
    solc:
        remappings:
            - "@aave=aave/protocol-v2@1.0.1"
        vyper:
            version: null

wallets:
    development:
        primary_public_key: ${GANACHE_1_PUBLIC_KEY}
        secondary_public_key: ${GANACHE_2_PUBLIC_KEY}
        primary_private_key: ${GANACHE_1_PRIVATE_KEY}
        secondary_private_key: ${GANACHE_2_PRIVATE_KEY}
    mainnet-fork-dev:
        primary_public_key: ${GANACHE_1_PUBLIC_KEY}
        secondary_public_key: ${GANACHE_2_PUBLIC_KEY}
        primary_private_key: ${GANACHE_1_PRIVATE_KEY}
        secondary_private_key: ${GANACHE_2_PRIVATE_KEY}
    rinkeby:
        primary_private_key: ${PRIMARY_PRIVATE_KEY}
        secondary_private_key: ${SECONDARY_PRIVATE_KEY}
    kovan:
        primary_private_key: ${PRIMARY_PRIVATE_KEY}
        secondary_private_key: ${SECONDARY_PRIVATE_KEY}
    alchemy-kovan:
        primary_private_key: ${PRIMARY_PRIVATE_KEY}
        secondary_private_key: ${SECONDARY_PRIVATE_KEY}
    ganache-cli-local:
        primary_public_key: ${GANACHE_1_PUBLIC_KEY}
        secondary_public_key: ${GANACHE_2_PUBLIC_KEY}

project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: mainnet-fork-dev
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
            port: 8555
            mnemonic: nerve alone rebuild ability bean rare moral belt saddle census normal trend
        verify: False
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false
    rinkeby:
        verify: True
    kovan:
        verify: True
        weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
        lending_pool_addresses_provider: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
    alchemy-kovan:
        verify: True
        weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
        lending_pool_addresses_provider: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
    mainnet-fork-dev:
        cmd_settings:
            port: 8555
            chain_id: 1447
            mnemonic: nerve alone rebuild ability bean rare moral belt saddle census normal trend
        weth_token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
        lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
        verify: False
    ganache-cli-local:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
            port: 8555
            chain_id: 1447
            mnemonic: nerve alone rebuild ability bean rare moral belt saddle census normal trend
        verify: False

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dev_deployment_artifacts: false
