dotenv: .env

dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0

compiler:
  evm_version: null
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"

wallets:
  development:
    primary_public_key: ${GANACHE_1_PUBLIC_KEY}
    secondary_public_key: ${GANACHE_2_PUBLIC_KEY}
    primary_private_key: ${GANACHE_1_PRIVATE_KEY}
    secondary_private_key: ${GANACHE_2_PRIVATE_KEY}
  rinkeby:
    primary_private_key: ${PRIMARY_PRIVATE_KEY}
    secondary_private_key: ${SECONDARY_PRIVATE_KEY}
  alchemy-rinkeby:
    primary_private_key: ${PRIMARY_PRIVATE_KEY}
    secondary_private_key: ${SECONDARY_PRIVATE_KEY}
  mainnet-fork-dev:
    primary_private_key: ${GANACHE_1_PRIVATE_KEY}
    secondary_private_key: ${GANACHE_2_PRIVATE_KEYs}

networks:
  default: development
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings:
      port: 8555
      mnemonic: nerve alone rebuild ability bean rare moral belt saddle census normal trend
    verify: False
  rinkeby:
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    verify: True
  alchemy-rinkeby:
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    cmd_settings:
      port: 8555
      chain_id: 1447
      mnemonic: nerve alone rebuild ability bean rare moral belt saddle census normal trend
    verify: False
