dotenv: .env

dependencies:
    # - <organization/repo>@<version>
    - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
    evm_version: null
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
        vyper:
            version: null

wallets:
    development:
        primary_public_key: ${GANACHE_1_PUBLIC_KEY}
        secondary_public_key: ${GANACHE_2_PUBLIC_KEY}
        primary_private_key: ${GANACHE_1_PRIVATE_KEY}
        secondary_private_key: ${GANACHE_2_PRIVATE_KEY}
    mainnet-fork-dev:
        primary_private_key: ${PRIMARY_PRIVATE_KEY}
        secondary_private_key: ${SECONDARY_PRIVATE_KEY}
    rinkeby:
        primary_private_key: ${PRIMARY_PRIVATE_KEY}
        secondary_private_key: ${SECONDARY_PRIVATE_KEY}
    kovan:
        primary_private_key: ${PRIMARY_PRIVATE_KEY}
        secondary_private_key: ${SECONDARY_PRIVATE_KEY}
    ganache-cli-local:
        primary_public_key: ${GANACHE_1_PUBLIC_KEY}
        secondary_public_key: ${GANACHE_2_PUBLIC_KEY}

project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
            port: 8555
            mnemonic: nerve alone rebuild ability bean rare moral belt saddle census normal trend
        verify: False
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false
    rinkeby:
        eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
        verify: True
    kovan:
        eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
        verify: True
    mainnet-fork-dev:
        eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
        verify: False
    ganache-cli-local:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
            port: 8555
            chain_id: 1447
            mnemonic: nerve alone rebuild ability bean rare moral belt saddle census normal trend
        verify: False

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dev_deployment_artifacts: false
